//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concour()
        {
            this.Inscriptions = new HashSet<Inscription>();
        }
    
        public int ID_concours { get; set; }
        public string Nom_concours { get; set; }
        public Nullable<System.DateTime> Date_concours { get; set; }
        public Nullable<System.DateTime> Date_limite { get; set; }
        public Nullable<int> Nombre_de_poste { get; set; }
        public Nullable<int> ID_grade { get; set; }
        public string Statut { get; set; }
    
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
    }
}
