//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Gestionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gestionnaire()
        {
            this.Inscriptions = new HashSet<Inscription>();
        }
    
        public int ID_gestionnaire { get; set; }
        public string Nom_gestionnaire { get; set; }
        public string Prénom_gestionnaire { get; set; }
        public string Adresse_mail { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ce champ est requis.")]
        public string mot_de_passe { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ce champ est requis.")]
        public string confirmer_mot_de_passe {​​​​​​​ get; set; }​​​​​​​
        [DataType(DataType.Password)]
        [DisplayName("Confimer mot de passe")]
        [Compare("mot_de_passe")]


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscription> Inscriptions { get; set; }
    }
}

